### ISSUE TITLE
Add a -version flag

### ISSUE THREAD

**Issue by kytrinyx** [exercism/blazon#7]
If you have a blazon executable, it's impossible to know which version is installed.

**Comment by ferhatelmas** [comment]
@kytrinyx Which one? Constant in source code or ldflags or ... ?

**Comment by kytrinyx** [comment]
I'd say constant in source code with an explicit `-version` flag. We could consider using the http://github.com/spf13/cobra library which is very neat and tidy and comes with some useful things out of the box (version, usage/help, etc).
